-- Runtime replacement only; applied Foundation schema/data/ACL remain unchanged.
create or replace function public.sync_feedback_comment_count() returns trigger language plpgsql security invoker set search_path='' as $$ begin if tg_op='INSERT' then update public.feedback set comments=comments+1 where id=new.feedback_id; return new; elsif tg_op='DELETE' then update public.feedback set comments=greatest(0,comments-1) where id=old.feedback_id; return old; end if; return null; end; $$;

create or replace function private.feedback_rate_limit_consume(p_action text,p_actor text,p_ip text) returns table(allowed boolean,retry_after_seconds integer) language plpgsql security definer set search_path='' as $$
declare v_rule integer[]; v_window_seconds integer; v_actor_limit integer; v_ip_limit integer; v_global_limit integer; v_window_started_at timestamptz; v_actor_hash text; v_ip_hash text; v_global_hash text; v_actor_allowed boolean; v_ip_allowed boolean; v_global_allowed boolean; v_retry_after_seconds integer; v_affected integer;
begin
 v_rule:=private.feedback_rate_rule(p_action); if v_rule is null or pg_catalog.cardinality(v_rule)<>4 then raise exception using errcode='22023',message='invalid_rate_limit_action'; end if; v_window_seconds:=v_rule[1]; v_actor_limit:=v_rule[2]; v_ip_limit:=v_rule[3]; v_global_limit:=v_rule[4];
 v_window_started_at:=pg_catalog.to_timestamp(pg_catalog.floor(extract(epoch from pg_catalog.clock_timestamp())/v_window_seconds)*v_window_seconds); v_retry_after_seconds:=greatest(1,v_window_seconds-pg_catalog.floor(extract(epoch from pg_catalog.clock_timestamp()-v_window_started_at))::integer);
 v_actor_hash:=private.feedback_hmac('actor:'||p_actor); v_ip_hash:=private.feedback_hmac('ip:'||p_ip); v_global_hash:=private.feedback_hmac('global:'||p_action);
 insert into private.feedback_rate_limit_windows as q values('actor',v_actor_hash,p_action,v_window_started_at,1) on conflict(scope,scope_hash,action,window_started_at) do update set request_count=q.request_count+1 where q.request_count<v_actor_limit; get diagnostics v_affected=row_count; v_actor_allowed:=v_affected=1;
 insert into private.feedback_rate_limit_windows as q values('ip',v_ip_hash,p_action,v_window_started_at,1) on conflict(scope,scope_hash,action,window_started_at) do update set request_count=q.request_count+1 where q.request_count<v_ip_limit; get diagnostics v_affected=row_count; v_ip_allowed:=v_affected=1;
 insert into private.feedback_rate_limit_windows as q values('global',v_global_hash,p_action,v_window_started_at,1) on conflict(scope,scope_hash,action,window_started_at) do update set request_count=q.request_count+1 where q.request_count<v_global_limit; get diagnostics v_affected=row_count; v_global_allowed:=v_affected=1;
 allowed:=v_actor_allowed and v_ip_allowed and v_global_allowed; retry_after_seconds:=case when allowed then 0 else v_retry_after_seconds end; return next; return;
end; $$;

grant feedback_writer to postgres with inherit false, set true;
grant create on schema public to feedback_writer;
set local role feedback_writer;
-- The following three definitions preserve the applied bodies; only special expressions are unqualified.
create or replace function public.feedback_create(p_project text,p_type text,p_title text,p_body text,p_author text,p_actor text,p_ip text) returns jsonb language plpgsql security definer set search_path='' as $$
declare e text; rate record; idv text; t timestamptz; authorv text; hashv text; ip_bucket text;
begin
 if p_project is null or p_project not in('threadr','loomi','stackbench','notedeck','general') then return pg_catalog.jsonb_build_object('ok',false,'error','invalid_project'); end if; if p_type is null or p_type not in('bug','feature','improve','other') then return pg_catalog.jsonb_build_object('ok',false,'error','invalid_type'); end if; if p_title is null or pg_catalog.btrim(p_title)='' or pg_catalog.char_length(p_title)>80 then return pg_catalog.jsonb_build_object('ok',false,'error','invalid_title'); end if; if p_body is null or pg_catalog.btrim(p_body)='' or pg_catalog.char_length(p_body)>800 then return pg_catalog.jsonb_build_object('ok',false,'error','invalid_body'); end if; if p_author is not null and p_author<>'' and (pg_catalog.btrim(p_author)='' or pg_catalog.char_length(p_author)>24) then return pg_catalog.jsonb_build_object('ok',false,'error','invalid_author'); end if;
 e:=private.feedback_valid_actor_ip(p_actor,p_ip); if e is not null then return pg_catalog.jsonb_build_object('ok',false,'error',e); end if; ip_bucket:=private.feedback_canonical_ip(p_ip); select * into rate from private.feedback_rate_limit_consume('feedback.create',p_actor,ip_bucket); if not rate.allowed then return pg_catalog.jsonb_build_object('ok',false,'error','rate_limited','retry_after_seconds',rate.retry_after_seconds); end if;
 idv:='u'||pg_catalog.encode(extensions.gen_random_bytes(16),'hex'); t:=pg_catalog.clock_timestamp(); authorv:=coalesce(nullif(p_author,''),'익명'); hashv:=private.feedback_hmac('actor:'||p_actor); insert into public.feedback(id,project,type,status,title,body,author,date,votes,comments,tags) values(idv,p_project,p_type,'open',p_title,p_body,authorv,t,1,0,array[]::text[]); insert into public.feedback_votes(feedback_id,voter_id) values(idv,hashv); return pg_catalog.jsonb_build_object('ok',true,'id',idv,'project',p_project,'type',p_type,'status','open','title',p_title,'body',p_body,'author',authorv,'date',t,'votes',1,'comments',0,'voted',true);
end; $$;
create or replace function public.feedback_comment_create(p_feedback_id text,p_author text,p_body text,p_actor text,p_ip text) returns jsonb language plpgsql security definer set search_path='' as $$
declare e text; rate record; idv text; t timestamptz; authorv text; ip_bucket text;
begin
 if p_feedback_id is null or p_feedback_id !~ '^[A-Za-z0-9_-]{1,64}$' then return pg_catalog.jsonb_build_object('ok',false,'error','invalid_feedback_id'); end if; if p_body is null or pg_catalog.btrim(p_body)='' or pg_catalog.char_length(p_body)>500 then return pg_catalog.jsonb_build_object('ok',false,'error','invalid_body'); end if; if p_author is not null and p_author<>'' and (pg_catalog.btrim(p_author)='' or pg_catalog.char_length(p_author)>24) then return pg_catalog.jsonb_build_object('ok',false,'error','invalid_author'); end if; e:=private.feedback_valid_actor_ip(p_actor,p_ip); if e is not null then return pg_catalog.jsonb_build_object('ok',false,'error',e); end if; ip_bucket:=private.feedback_canonical_ip(p_ip); select * into rate from private.feedback_rate_limit_consume('comment.create',p_actor,ip_bucket); if not rate.allowed then return pg_catalog.jsonb_build_object('ok',false,'error','rate_limited','retry_after_seconds',rate.retry_after_seconds); end if; perform 1 from public.feedback where id=p_feedback_id for update; if not found then return pg_catalog.jsonb_build_object('ok',false,'error','feedback_not_found'); end if;
 idv:='c'||pg_catalog.encode(extensions.gen_random_bytes(16),'hex'); t:=pg_catalog.clock_timestamp(); authorv:=coalesce(nullif(p_author,''),'익명'); insert into public.feedback_comments(id,feedback_id,author,body,voter_id,created_at) values(idv,p_feedback_id,authorv,p_body,private.feedback_hmac('actor:'||p_actor),t); return pg_catalog.jsonb_build_object('ok',true,'id',idv,'feedback_id',p_feedback_id,'author',authorv,'body',p_body,'created_at',t);
end; $$;
create or replace function public.feedback_vote_set(p_feedback_id text,p_voted boolean,p_actor text,p_ip text) returns jsonb language plpgsql security definer set search_path='' as $$
declare e text; rate record; h text; n integer; active boolean; logical_was_voted boolean; inserted boolean:=false; deleted integer:=0; votesv integer; votedv boolean; ip_bucket text;
begin
 if p_feedback_id is null or p_feedback_id !~ '^[A-Za-z0-9_-]{1,64}$' then return pg_catalog.jsonb_build_object('ok',false,'error','invalid_feedback_id'); end if; if p_voted is null then return pg_catalog.jsonb_build_object('ok',false,'error','invalid_voted'); end if; e:=private.feedback_valid_actor_ip(p_actor,p_ip); if e is not null then return pg_catalog.jsonb_build_object('ok',false,'error',e); end if; ip_bucket:=private.feedback_canonical_ip(p_ip); select * into rate from private.feedback_rate_limit_consume('vote.set',p_actor,ip_bucket); if not rate.allowed then return pg_catalog.jsonb_build_object('ok',false,'error','rate_limited','retry_after_seconds',rate.retry_after_seconds); end if;
 select votes into votesv from public.feedback where id=p_feedback_id for update; if not found then return pg_catalog.jsonb_build_object('ok',false,'error','feedback_not_found'); end if; h:=private.feedback_hmac('actor:'||p_actor); perform 1 from public.feedback_votes where feedback_id=p_feedback_id and (voter_id=p_actor or voter_id in(select actor_hash from private.feedback_actor_hashes(p_actor))) for update; select count(*),coalesce(bool_or(voter_id=h),false) into n,active from public.feedback_votes where feedback_id=p_feedback_id and (voter_id=p_actor or voter_id in(select actor_hash from private.feedback_actor_hashes(p_actor))); logical_was_voted:=n>0;
 if p_voted then if not active then insert into public.feedback_votes(feedback_id,voter_id) values(p_feedback_id,h) on conflict do nothing returning true into inserted; inserted:=coalesce(inserted,false); if inserted and n=0 then update public.feedback set votes=votes+1 where id=p_feedback_id returning votes into votesv; end if; end if; delete from public.feedback_votes where feedback_id=p_feedback_id and voter_id<>h and (voter_id=p_actor or voter_id in(select actor_hash from private.feedback_actor_hashes(p_actor))); else delete from public.feedback_votes where feedback_id=p_feedback_id and (voter_id=p_actor or voter_id in(select actor_hash from private.feedback_actor_hashes(p_actor))); get diagnostics deleted=row_count; if deleted>0 then update public.feedback set votes=greatest(0,votes-1) where id=p_feedback_id returning votes into votesv; end if; end if;
 select exists(select 1 from public.feedback_votes where feedback_id=p_feedback_id and voter_id=h) into votedv; return pg_catalog.jsonb_build_object('ok',true,'feedback_id',p_feedback_id,'votes',votesv,'voted',votedv,'changed',case when p_voted then not logical_was_voted else logical_was_voted end);
end; $$;
reset role;
revoke create on schema public from feedback_writer;
revoke set option for feedback_writer from postgres;
